PR for Feature Branch into Development Branch
tadeuasarro/WeatherApp pull request #1
Opened 2020-12-02 21:36 UTC by tadeuasarro

### The purpose of this pull request is to evaluate the Feature branch and merge it into de Development branch.

### Features
- Input the desired city into a search;
- Info about temperatures, weather conditions, wind speed, and humidity.

2020-12-02 22:19 UTC, Forison requested changes
## Status:: Changes Required🔴
# 🙋‍♂️ @tadeuasarro,
#### You have done a good job so far, on this one, here are a few changes we have to make to get the project approved 😊.
* [ ] It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- There should be a button that enables users to toggle the value of the temperature to a degree celsius or Fahrenheit
* [ ] It changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
-  Use your own discretion to use an image, color, or a gif to set up a range to match the temperature readings, of the selected location.
* [ ] Check my comments below as well👇
### That is it kindly address the issue and proceed to the next task🤗.
#### Happy coding👨‍💻
Addo Forison

2020-12-02 22:19 UTC, Forison commented on src/index.js
> +        alert('Invalid city, please try again!');
* [ ] Do not use Windows.alert(). It’s ugly, impossible to style, stop code execution, and display differently on different browsers. Use custom modal instead
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/alert_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/javascript-module-v-10/166782/path/step/97634928/)).

2020-12-02 22:19 UTC, Forison commented on src/weather.js
> +    const response = await fetch(`http://api.openweathermap.org/data/2.5/weather?q=${cityName}&units=metric&appid=873aa78430c524e7ef6505af11e25a57`, { mode: 'cors' });
**[OPTIONAL]** 
* [ ] Kindly use a `try and catch` statement to handle your API request or any other means that would enable you to capture exceptions in a much cleaner way.

2020-12-03 19:54 UTC, uche-inyama approved these changes
## Approved

### Hi Tadeuasarro :wave: 

Go on with the next task.

### ``` Have a great day ``` 

``` Uchechukwu Henry Inyama ```

2020-12-03 20:18 UTC, merged